services:
  - type: web
    name: gym-tracker
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    autoDeploy: true
